'on':
  workflow_dispatch: ~
  schedule:
  - cron: 25 17 * * 5
name: update
jobs:
  update:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: r-lib/actions/setup-r@v2

    - name: Query dependencies
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - name: Restore R package cache
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds')
          }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

    - name: Install dependencies
      run: |
        install.packages(c("devtools"))
        devtools::install_deps(dependencies = TRUE, type = "binary")
      shell: Rscript {0}

    - name: Checkout output branch
      uses: actions/checkout@v3
      with:
        ref: output
        path: output

    - name: Update output
      run: |
        devtools::load_all()
        write_fflecsi_gtfs_flex("output/fflecsi.gtfs")
        get_sfc_for_fflecsi_locations() |> sf::write_sf("output/fflecsi.geojson")
      shell: Rscript {0}

    - name: Commit new output
      if: github.ref == 'refs/heads/main'
      run: |
        cd output
        git config user.name "Update Bot"
        git config user.email "<>"
        git add .
        git commit --allow-empty -m "Updated for new release"
        git push origin output
        cd ..